### ISSUE TITLE
Question `foundations/question-023.md` is incorrect

### ISSUE THREAD

**Issue by StefH** [FidelusAleksander/ghcertified#200]
The question is: `Is GitHub Copilot free to use?`
Your answer is `No`, however this is not correct anymore.

GitHub states:
> GitHub Copilot is free to use for verified students, teachers, and maintainers of popular open source projects. If you are not a student, teacher, or maintainer of a popular open source project, you can try GitHub Copilot for free with a one-time 30-day trial. After the free trial, you will need a paid subscription for continued use.

See https://docs.github.com/en/copilot/quickstart

**Comment by FidelusAleksander** [comment]
Thanks for raising this @StefH :raised_hands: 

You are right, there are exceptions and in some cases Copilot can be free (for some people or for a trial). That said, personally If I had a question `Is GitHub Copilot free to use` on the official exam and the only answers were `Yes` or `No` I would still choose `No`.  You can expect the official exam to contain answers where it's not always crystal clear what to choose.

I think @rilindo captured this nicely in https://github.com/FidelusAleksander/ghcertified/pull/201 so I will go ahead and close this issue. :rocket:

_P.S: If you find any other issues don't hesitate to raise an Issue or open a PR_
