### ISSUE TITLE
Error in foundations/question-76

### ISSUE THREAD

**Issue by CamiCasus** [FidelusAleksander/ghcertified#214]
**Describe the issue**

The answer to[ Github foundations Question 076](https://github.com/FidelusAleksander/ghcertified/blob/master/content/questions/foundations/question-076.md) is wrong because acording to this documentation https://docs.github.com/en/get-started/learning-about-github/githubs-plans#github-pro there is a PRO princing plan

**Additional context**

**Comment by rilindo** [comment]
The question refers to the Organization plans, which is listed as follows:

![image](https://github.com/FidelusAleksander/ghcertified/assets/1043059/aa742813-c013-4b35-ad7d-466205c6a537)

The pro plan is for individuals:

![image](https://github.com/FidelusAleksander/ghcertified/assets/1043059/4ce34be1-849f-4513-80c4-7b021f36c826)

Given that, though, I'll add a question to include the plans for individuals

**Comment by CamiCasus** [comment]
Ohhh I see, my bad

**Comment by FidelusAleksander** [comment]
Thanks for raising this issue @CamiCasus  :+1: 

@rilindo clarified this nicely in https://github.com/FidelusAleksander/ghcertified/pull/216 so I will go ahead and close this issue.

If you find any other things that are not clear or seem wrong - please raise an issue again :smiley:
