### ISSUE TITLE
Question foundations/question-099.md needs changes

### ISSUE THREAD

**Issue by CamiCasus** [FidelusAleksander/ghcertified#217]
**Describe the issue**

There is a duplicated alternative in this question
One of these options should be removed or maybe changed to: 
- [ ] Close and remove

or another option you consider more appropriated

![image](https://github.com/FidelusAleksander/ghcertified/assets/3966777/3d8f401a-ee8d-4c54-9a59-79323668b611)

**Comment by rilindo** [comment]
Confirmed, @CamiCasus 

![image](https://github.com/FidelusAleksander/ghcertified/assets/1043059/0fa96c1e-4686-4dcd-879c-224ffa99db96)


I recommend you replace one of the dups with an alternative [here](https://github.com/FidelusAleksander/ghcertified/blob/5ce0c9ee0bde5f5a047a9a7dfc870ae064ce8de1/content/questions/foundations/question-099.md?plain=1#L9-L13)  if you are comfortable creating a PR.

**Comment by rilindo** [comment]
@CamiCasus To be clear, you are free to create a PR. I could create a PR, but the last time I have inadvertently stomped on your PR (sorry!), so this is your opportunity to contribute and up your GitHub stats. :)

**Comment by CamiCasus** [comment]
Don't worry @rilindo, ok tomorrow I'll make a pull request with the change in the question, thanks
