### ISSUE TITLE
Github foundations practice test - typo

### ISSUE THREAD

**Issue by ChrisHLC** [FidelusAleksander/ghcertified#231]
**Describe the issue**

I think that there is a typo in the second answer

**Additional context**

![2024-05-23 19_55_20-Window](https://github.com/FidelusAleksander/ghcertified/assets/33631473/0212e458-e871-4c79-bd25-6fd33e17aadd)

**Comment by FidelusAleksander** [comment]
Yeah, that one looks odd. If no1 else picks it up then I will fix next week.

Thanks for raising the issue!

**Comment by FidelusAleksander** [comment]
Fixed in https://github.com/FidelusAleksander/ghcertified/pull/233

Thanks for raising the issue @ChrisHLC :rocket:
