### ISSUE TITLE
Enable progress saving

### ISSUE THREAD

**Issue by shelar1423** [FidelusAleksander/ghcertified#246]
**Please describe the feature you feel like this repository should have.**
the user login option should be added to save users test progress, suddenly after a misclick reload i lost my whole progress  i was at 100th question 😢 

**Additional context**

**Comment by FidelusAleksander** [comment]
Hi - thanks for raising the issue @shelar1423 

It's something to consider as I've heard this feedback before. That said I don't have the time or frontend experiance to work on this myself.

If someone proposes here a solution (to be accepted prior to implementation) that is simple to code and more importantly to **maintain** then I wouldn't oppose.
