### ISSUE TITLE
Foundation Exam Question MD. No, 105

### ISSUE THREAD

**Issue by shukfanchung** [FidelusAleksander/ghcertified#248]
Hi there,
I noticed the following issue:

**Describe the issue**
![FoundationQ105](https://github.com/FidelusAleksander/ghcertified/assets/138369200/c28f67c7-2893-4359-ab27-d83ad0dd407d)

The answers should not include 'Amount of code line additions and deletions' as this appears in the Code Frequency section in the Insight Tab. 

**Additional context**
[ghcertified](https://github.com/FidelusAleksander/ghcertified/tree/master)/[content](https://github.com/FidelusAleksander/ghcertified/tree/master/content)/[questions](https://github.com/FidelusAleksander/ghcertified/tree/master/content/questions)/[foundations](https://github.com/FidelusAleksander/ghcertified/tree/master/content/questions/foundations)
/question-105.md

**Comment by FidelusAleksander** [comment]
Hi

That information is also available in `Pulse` section. See [here](https://github.com/FidelusAleksander/ghcertified/pulse/monthly)
![image](https://github.com/FidelusAleksander/ghcertified/assets/63016446/2c8cf02e-9bb1-4c9e-bfb5-50a8752bf946)

Please re-open if this doesn't clarify
