### ISSUE TITLE
Github Action - Question 116 - answer may be outdated

### ISSUE THREAD

**Issue by marchalvincent** [FidelusAleksander/ghcertified#252]
Hello,

**Describe the issue**
Question 116, it is mentioned that you can delete a workflow run when it is 2 weeks old but I'm able to delete a workflow as soon as it has been completed.

**Additional context**
The [github doc](https://docs.github.com/en/actions/managing-workflow-runs/deleting-a-workflow-run) linked in the question shows an example with a workflow run which is 11 minutes old.

There is a third given answer which is also true but not accepted as a good answer "When workflow run is 10 days old". It may leads to misunderstanding.

We may update the right answer allowing only one answer: "When workflow run has been completed" or "As soon as a workflow run has been completed".

Have a nice day.
Vincent Marchal

**Comment by FidelusAleksander** [comment]
Hi @marchalvincent !

Thanks for raising this issue. I see your point. 

Would you like to take a stab at it and open a pull request with a proposed fix?

c.c @dostonhamrakulov since you just recently contributed mentioned question
