### ISSUE TITLE
GitHub Foundations - Question 105 alternatives

### ISSUE THREAD

**Issue by Shyuu7** [FidelusAleksander/ghcertified#253]
**Describe the issue**
Question asks specifically what's the info available on the Pulse section of the Insights tab, and allows for 4 different answers. While I do know that it shows a summary of the repo activity, I find that the other alternatives just seem... wrong? Or at least incorrectly worded?

**Additional context**
The [documentation page](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/using-pulse-to-view-a-summary-of-repository-activity) linked on the hint section says the following:

> You can view an overview of a repository's activity through Pulse. Pulse includes a list of open and merged pull requests, open and closed issues, and a graph showing the commit activity for the top 15 users who committed to the default branch of the project in the selected time period.

So "Summary of Repository Activity", "List of Issue discussions" and "Pull requests open/merged ratio" seem somewhat correct, but the other 3 ("Amount of code line additions and deletions", "Amount of forks of the repo" and "List of unresolved conversations") are from other sections of the Insight tab, not from Pulse.

**Comment by FidelusAleksander** [comment]
Hi @Shyuu7 

Seems similar to https://github.com/FidelusAleksander/ghcertified/issues/235

I think the issue is that Pulse only shows these sections if they are not empty, e.g
- If there are any unresolved conversations, then that will be shown in Pulse section, see [CodeQL Pulse](https://github.com/github/codeql/pulse) as an example

**Comment by Shyuu7** [comment]
Ah yes, apologies. I even skimmed the issues tab for a similar question but seems like I missed it.

That indeed seems to be the problem; the repo I was checking out didn't have any open discussions, and with the fact that the documentation linked didn't mention that at all left me very confused.

Thanks for answering! Now that I've passed the cert I'll surely make time to contribute with some questions.
