### ISSUE TITLE
Incorrect answer for question Who will be notified when a NEW secret is pushed and detected in a repository? 

### ISSUE THREAD

**Issue by carlos-quintero** [FidelusAleksander/ghcertified#262]
In practice exam Advanced Security, question 17

”Who will be notified when a NEW secret is pushed and detected in a repository? “ 

(https://github.com/FidelusAleksander/ghcertified/blob/master/content/questions/advanced_security/question-017.md)

the answer “Commit authors” should be included since incremental scans notify them. See:

> Note
> 
> Commit authors who've accidentally committed secrets will be notified, regardless of their notification preferences.

Reference:

https://docs.github.com/en/code-security/secret-scanning/managing-alerts-from-secret-scanning/monitoring-alerts#incremental-scans

BTW the link provided in the question is incorrect, the correct is the one above.

**Comment by FidelusAleksander** [comment]
Hi @carlos-quintero !

Seems you are right here. If you would like to update the answers, take a look at the [contributing guide](https://github.com/FidelusAleksander/ghcertified/blob/master/CONTRIBUTING.md#updating-existing-content). 
If not - I will fix it myself in the following days

Thanks for raising the issue :rocket:

**Comment by FidelusAleksander** [comment]
Done in #269 

Thanks for raising the issue :rocket:
