### ISSUE TITLE
Incorrect answer for question “ Which of the following statements about enabling CodeQL scanning default setup are true?”

### ISSUE THREAD

**Issue by carlos-quintero** [FidelusAleksander/ghcertified#263]
In practice exam GitHub Advanced Security, question 74:

> Which of the following statements about enabling CodeQL scanning default setup are true?

the following answer is also correct:

> You can enable default setup on any repository, regardless of the contents of the repository

See:

> A repository must meet all the following criteria to be eligible for default setup, otherwise you need to use advanced setup.
> 
> - Code scanning is not already enabled.
> - GitHub Actions are enabled.
> - Publicly visible.
> 
> We recommend enabling default setup for eligible repositories if there is any chance the repositories will include at least one CodeQL-supported language in the future. If you enable default setup on a repository that does not include any CodeQL-supported languages, default setup will not run any scans or use any GitHub Actions minutes. If CodeQL-supported languages are added to the repository, default setup will automatically begin scanning CodeQL-supported languages and using GitHub Actions minutes.

Reference:
https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning-at-scale#eligible-repositories-for-codeql-default-setup-at-scale

**Comment by FidelusAleksander** [comment]
Hey @carlos-quintero 

Taking a quick look and seems you are right. 

When I'm trying to remember the past - I'm almost sure it wasn't like that few months ago, meaning you couldn't turn on CodeQL unless the repository contained one of the supported languages. Maybe that was changes by GitHub

Would you like to create a PR to fix this? It's fairly easy [[docs](https://github.com/FidelusAleksander/ghcertified/blob/master/CONTRIBUTING.md#updating-existing-content)]

Thanks for raising the issue! :rocket:

**Comment by FidelusAleksander** [comment]
Done in #269 

Thanks for raising the issue :rocket:
