### ISSUE TITLE
Highlighted text in code section

### ISSUE THREAD

**Issue by icepick4** [FidelusAleksander/ghcertified#271]
**Describe the bug**

When the word searched is in a code section, it shows up with `<mark>`  tags and not highlighted.

**To Reproduce**
1. Search the word "cache"
2. Go on the question 97 from GitHub actions.
3. Look at the title

**Expected behavior**
The text should be highlighted

**Screenshots**
![image](https://github.com/user-attachments/assets/74557113-e5a0-429e-9aea-0c45f0988f3c)

**Additional context**
I know it is not a important issue and it is not happening on a lot of question maybe but it is still there.

**Comment by FidelusAleksander** [comment]
Hi @icepick4 

I can't seem to reproduce this myself on Windows 10 using Chrome or Microsoft Edge browsers

![image](https://github.com/user-attachments/assets/b27c3eac-08d6-47e1-8b5d-fcb7be800b57)

Either way, this "question" plugin is a [third party library](https://github.com/bonartm/quizdown-js) that has little to no maintenance so I highly doubt there would be a quick fix for that

With all that in mind - I will close this bug report

Thanks for raising the issue !

**Comment by icepick4** [comment]
Hey @FidelusAleksander,

Sorry I did not mentionned that it is when you search with search bar on top left. Not with CTRL+F.

![image](https://github.com/user-attachments/assets/e78a3952-3423-4d4e-be53-c83d67bf7ae4)

Ok I understand. I will submit the issue on the repo.
