### ISSUE TITLE
Refinement of question

### ISSUE THREAD

**Issue by gauravpatel67** [FidelusAleksander/ghcertified#295]
**Describe the issue**

 How does the synchronization between GitHub projects and issues and pull requests work?
 This question is grammatically tough to read and it should be
 How does the synchronization between GitHub projects, issues and pull requests work?
**Additional Details**
It is in github foundation practice test.

**Comment by FidelusAleksander** [comment]
Hey @gauravpatel67 

If you want to propose that change I'm okay to merge it 😄 

See https://github.com/FidelusAleksander/ghcertified/blob/master/CONTRIBUTING.md
